import { useEffect, useRef, useState } from 'react';
import Layout from '../components/Layout';
import { useAuth } from '../auth/auth-context';
import { StatusAlert } from '../components/Feedback';
import { changePassword, deleteProfilePhoto, updateProfile, uploadProfilePhoto } from '../services/api';

function ProfilePage(){
 const {user,updateUser}=useAuth();
 const [form,setForm]=useState({name:'',phone:'',department:''});
 const [password,setPassword]=useState({current_password:'',password:'',password_confirmation:''});
 const [feedback,setFeedback]=useState(null);const [saving,setSaving]=useState(false);const [photoBusy,setPhotoBusy]=useState(false);const fileRef=useRef(null);
 useEffect(()=>setForm({name:user?.name||'',phone:user?.phone||'',department:user?.department||''}),[user]);
 const submitProfile=async(e)=>{e.preventDefault();setSaving(true);setFeedback(null);try{const r=await updateProfile(form);updateUser(r.data.user);setFeedback({variant:'success',message:r.data.message});}catch(err){setFeedback({variant:'danger',message:err.message});}finally{setSaving(false);}};
 const submitPassword=async(e)=>{e.preventDefault();setSaving(true);setFeedback(null);try{const r=await changePassword(password);setPassword({current_password:'',password:'',password_confirmation:''});setFeedback({variant:'success',message:r.data.message});}catch(err){setFeedback({variant:'danger',message:err.message});}finally{setSaving(false);}};
 const upload=async(e)=>{const photo=e.target.files?.[0];if(!photo)return;setPhotoBusy(true);setFeedback(null);try{const r=await uploadProfilePhoto(photo);updateUser(r.data.user);setFeedback({variant:'success',message:r.data.message});}catch(err){setFeedback({variant:'danger',message:err.message});}finally{setPhotoBusy(false);e.target.value='';}};
 const remove=async()=>{setPhotoBusy(true);setFeedback(null);try{const r=await deleteProfilePhoto();updateUser(r.data.user);setFeedback({variant:'success',message:r.data.message});}catch(err){setFeedback({variant:'danger',message:err.message});}finally{setPhotoBusy(false);}};
 const initials=user?.name?.slice(0,2).toUpperCase()||'US';
 return <Layout title="My Profile" subtitle="Your profile is securely saved and available across devices.">
  {feedback&&<StatusAlert variant={feedback.variant} message={feedback.message} onDismiss={()=>setFeedback(null)}/>}
  <div className="profile-hero mb-4"><div className="profile-hero-main"><div className="profile-photo-control"><div className="profile-photo-preview profile-photo-preview-lg">{user?.profile_photo_url?<img src={user.profile_photo_url} alt="Profile"/>:<span>{initials}</span>}</div><button type="button" className="profile-photo-edit-button" disabled={photoBusy} onClick={()=>fileRef.current?.click()}>{photoBusy?'Saving...':'Upload'}</button><input ref={fileRef} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></div><div><span className="eyebrow-label">Campus account</span><h3>{user?.name}</h3><p>{user?.department||'Department not set'} | {user?.role}</p>{user?.profile_photo_url&&<button type="button" className="btn btn-sm btn-outline-danger" disabled={photoBusy} onClick={remove}>Remove photo</button>}</div></div><div className="profile-hero-status"><span>Approval</span><strong className="text-capitalize">{user?.approval_status}</strong></div></div>
  <div className="row g-4">
   <div className="col-xl-7"><form className="card border-0 shadow-sm rounded-4 p-4 h-100" onSubmit={submitProfile}><div className="section-card-header mb-4"><span className="eyebrow-label text-primary">PROFILE INFORMATION</span><h5 className="fw-bold mb-0">Update personal details</h5></div><div className="row g-3"><div className="col-md-6"><label className="form-label">Full name</label><input className="form-control" required minLength="2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Phone number</label><input className="form-control" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="col-12"><label className="form-label">Department</label><input className="form-control" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Email</label><input className="form-control" value={user?.email||''} disabled/></div><div className="col-md-6"><label className="form-label">Student / Staff ID</label><input className="form-control" value={user?.student_id||user?.faculty_id||user?.admin_id||''} disabled/></div></div><button className="btn btn-primary mt-4" disabled={saving}>{saving?'Saving...':'Save profile'}</button></form></div>
   <div className="col-xl-5"><form className="card border-0 shadow-sm rounded-4 p-4" onSubmit={submitPassword}><div className="section-card-header mb-4"><span className="eyebrow-label text-primary">SECURITY</span><h5 className="fw-bold mb-0">Change password</h5></div><label className="form-label">Current password</label><input type="password" className="form-control mb-3" required value={password.current_password} onChange={e=>setPassword({...password,current_password:e.target.value})}/><label className="form-label">New password</label><input type="password" className="form-control mb-3" required value={password.password} onChange={e=>setPassword({...password,password:e.target.value})}/><label className="form-label">Confirm new password</label><input type="password" className="form-control" required value={password.password_confirmation} onChange={e=>setPassword({...password,password_confirmation:e.target.value})}/><small className="text-secondary mt-2">Use 8+ characters with uppercase, lowercase, number and symbol.</small><button className="btn btn-outline-primary mt-4" disabled={saving}>{saving?'Updating...':'Change password'}</button></form></div>
  </div>
 </Layout>;
}
export default ProfilePage;
